### ISSUE TITLE
Permanent node labels

### ISSUE THREAD

**Issue by shb84** [jupyrdf/ipyforcegraph#43]
## Elevator Pitch

Currently, `NodelLabels` are ephemeral (displayed upon hover). It would be useful to have a feature where all node labels could be displayed permanently at once. 

## Motivation

Seeing identifying information about many nodes at once helps interpret the graph.  

## Design Ideas

Image from https://studentwork.prattsi.org/infovis/visualization/visualizing-les-miserables-social-network-1862/:
 
![image](https://user-images.githubusercontent.com/34602621/218800157-412cc35c-f16a-4e06-8d84-95f1be2bd5b5.png)

**Comment by nrbgt** [comment]
Generalized [custom shapes](https://vasturiano.github.io/force-graph/example/custom-node-shape/) are of course super useful, but [this](https://vasturiano.github.io/force-graph/example/text-nodes/) is about what we're going to be able to do for complex text.

Under the hood, text would be a relatively complex `canvas`-based implementation, depending on how much of the following was parametrized (e.g. color, etc), in order to get proper click targets (the first example's text has a `0` sized one, but maybe it could "fudged"):

```ts
        .nodeCanvasObject((node, ctx, globalScale) => {
          const label = node.id;
          const fontSize = 12/globalScale;
          ctx.font = `${fontSize}px Sans-Serif`;
          const textWidth = ctx.measureText(label).width;
          const bckgDimensions = [textWidth, fontSize].map(n => n + fontSize * 0.2); // some padding

          ctx.fillStyle = 'rgba(255, 255, 255, 0.8)';
          ctx.fillRect(node.x - bckgDimensions[0] / 2, node.y - bckgDimensions[1] / 2, ...bckgDimensions);

          ctx.textAlign = 'center';
          ctx.textBaseline = 'middle';
          ctx.fillStyle = node.color;
          ctx.fillText(label, node.x, node.y);

          node.__bckgDimensions = bckgDimensions; // to re-use in nodePointerAreaPaint
        })
        .nodePointerAreaPaint((node, color, ctx) => {
          ctx.fillStyle = color;
          const bckgDimensions = node.__bckgDimensions;
          bckgDimensions && ctx.fillRect(node.x - bckgDimensions[0] / 2, node.y - bckgDimensions[1] / 2, ...bckgDimensions);
        });
```

It would have an _entirely different_ 3d implementation, to get to something like [this](https://vasturiano.github.io/3d-force-graph/example/html-nodes/), which is actually theoretically much simpler, as it can be straight-up HTML, and therefore easier to reason about.

It's _possible_ to semi-generalize [html2canvas](https://github.com/niklasvh/html2canvas), but (uncached) performance might be... very poor.

**Comment by shb84** [comment]
Thank you for this answer. The 3D example is really slick and would be great long term, but the first 2D example is a good starting place IMO which might answer the mail short term. Hopefully such a feature can buy its way onboard and evolve over time.

**Comment by zwelz3** [comment]
Sorry, trying to follow the discussion and issue status, so is this capability (to use text for nodes) in any capacity expected to be added in the near term? We may run into issues with providing 1:1 capability if we cannot use text for nodes.

**Comment by nrbgt** [comment]
The argument is doing generalized custom shapes, with text being one of the techniques, without limiting it to _only_ text.

**Comment by sanbales** [comment]
As per @nrbgt's recommendation, for the 2D case, we could use [this](https://github.com/lukix/declarative-canvas) library to allow for drawing on the canvas in a declarative way.

**Comment by sanbales** [comment]
@zwelz3 : can we put a screen capture of the generic example here to better illustrate the 1:1 capability?

**Comment by zwelz3** [comment]
@sanbales how's this
![electron_5r2ylFN2eL](https://user-images.githubusercontent.com/32652349/220442186-6ab57a36-8245-4bb6-833d-90617262d254.gif)
