### ISSUE TITLE
Create example app

### ISSUE THREAD

**Issue by nrbgt** [jupyrdf/ipyforcegraph#7]
## Elevator Pitch

Create a more full-featured example notebook application.

## Motivation

For a better demonstration of the capability (and value of being connected to the widget bus), create an annotated `App.ipynb` (with an `importnb` "for show" notebook that imports it)

## Design Ideas

- get a larger representative data set with a few thousand nodes/edges
  - use the force: maybe a star wars example
- create some linked views
  - a "map" 2d forcegraph showing all the data
  - a table of the same data
    - ideally, figure out  a way to do this by reference into one of the grid tools
  - enable selection
    - use the selection to (optionally) update the table
  - a 3d graph that shows the selected nodes (and relevant links)
   - allow expanding to `n` nearest neighbors from graph
- wrap in a `jupyterlab-deck` experience

**Comment by sanbales** [comment]
Trying to make an app based on the `Erdős degree 1` graph (the people that are one "hop" away from coauthoring a paper with Paul Erdős.

It has 6,927 nodes and 11,850 edges.  My plan is to add more data to the links, e.g., paper title, or number of common publications.

I tried to look at other options (like animals and their genus trees) but could not find a good source of data.  There was a decent data source for international ⚽ that we could use but it's hard to make 1,000s of nodes out of it because there are only so many countries.  Maybe a good example of a "smaller" graph though.

**Comment by nrbgt** [comment]
Some examples we could gin up within a running app (or with things lying around the repo):
- `yarn.lock`
- the `conda-lock` outputs
- the current state of widgets
- the current labextensions/plugins installed, maybe get access to signals

**Comment by nrbgt** [comment]
In quick investigations, we found in a lumino/lab application that we could get at:

- registered plugins
- their tokens
- their signals

if we can get at some additional information (such as the listeners) we might be able to get at some more info. Some of these, however, will lose some of their identifying information due to minification, etc.

The widget manager, and its relationship to extensions and loaded widget imports, and the backbone graph observers, may also provide some useful stuff, but we'd have to be careful to exclude the "beholding" force graph itself.
